TARGET_NAME := ALIEN_$(ALIEN_NAME)

$(call ensure_defined,$(TARGET_NAME)_SRC_DIR)
$(TARGET_NAME)_OUT_DIR := $(call MAKE_OUT_DIR,$($(TARGET_NAME)_SRC_DIR))

$(TARGET_NAME) := $($(TARGET_NAME)_TARGETS)
