TARGET_NAME := CSHARP_$(CSHARP_NAME)
$(call ensure_defined,$(TARGET_NAME)_SRC_DIR)

$(TARGET_NAME)_OUT_DIR := $(call MAKE_OUT_DIR,$($(TARGET_NAME)_SRC_DIR))
$(TARGET_NAME)_BASENAME := $(CSHARP_NAME)$(call CSC_SUFFIX,$($(TARGET_NAME)_TYPE))
ifneq (,$($(TARGET_NAME)_INSTALL))
 $(TARGET_NAME) := $(INSTALL_ROOT)/bin/$($(TARGET_NAME)_BASENAME)
else
 $(TARGET_NAME) := $($(TARGET_NAME)_OUT_DIR)/$($(TARGET_NAME)_BASENAME)
endif
