#pragma once

#include <chrono>

using namespace std;
using namespace chrono;

#define MANSION_GAME_INVITE_CD 15s
#define MANSION_BANQUET_INVITE_CD 5s
#define MANSION_RECORD_MAX_COUNT 100u
#define MANSION_FARM_LAND_MAX_COUNT 9u

#define ROOM_INVITE_CD 15s

#define ARENA_NORMAL_REWARD_PTTID 10000
#define ARENA_ACHIEVE_REWARD_PTTID 10001
#define ARENA_ACHIEVE_MAIL_PTTID 18

#define ARENA_INIT_GLADIATOR_COUNT 5000u

#define PLAYER_CUSTOM_ICON_COUNT 3

#define MAIL_EXPIRE_DURATION hours(24 * 30)

#define GUANPIN_HIGHEST_GPIN 19
#define GUANPIN_REVOLT_WDAY 6
#define GUANPIN_DIANSHI_WDAY_FIRST 1
#define GUANPIN_DIANSHI_WDAY_SECOND 4
#define GUANPIN_LOGIN_BROADCAST_GE_GPIN 12
#define GUANPIN_CHANGED_RECORDS_MAX 100

#define EQUIPMENT_CUSTOM_ARRAY_LIMIT 99

#define MARRIAGE_PK_SLOT_COUNT 3

#define STATS_WIDTH 50

#define ACTOR_MAX_PIN 18u

#define HUANZHUANG_SELECTION_COUNT 3
#define SPINE_SELECTION_COUNT 3

#define STAR_WISH_START_SYSTEM_CHAT_MINUTES 15
#define PK_CHALLENGE_SYSTEM_CHAT_MINUTES 15

#define LEAGUE_WAR_MAX_MATCH_SIZE 16
#define LEAGUE_WAR_MIN_MATCH_SIZE 8
#define LEAGUE_WAR_RANK_REWARD_PTTID 20000

#define JADE_MAX_PUT_ON_TYPE_COUNT 5u
#define JADE_LEVELUP_GIDS_COUNT 3

#define CHILD_ADOPT_DIVORCE_FAVOR_DURATION 24h

#define MIRROR_NAME_POOL_START 10u

#define AI_SEND_GIFT_COUNT 50

#define ACTIVITY_DAIYANREN_DAYS 7

#define CREATE_ROLE_FIRST_MAIL_PTTID 1

#define MAX_GMD_SID 10000u

#define REBATE_MAIL_ID 2000
#define COME_BACK_MAIL_ID 3000
