DROP TABLE IF EXISTS city;

CREATE TABLE IF NOT EXISTS cities (
gid BIGINT UNSIGNED NOT NULL UNIQUE,
data MEDIUMBLOB NOT NULL
)
CHARACTER SET = utf8
ENGINE = InnoDB;

DELIMITER $$

DROP PROCEDURE IF EXISTS add_city$$
CREATE PROCEDURE add_city (IN param1 BIGINT UNSIGNED, IN param2 MEDIUMBLOB)
BEGIN
INSERT INTO cities(gid, data)
VALUES(param1, param2);
END$$

DROP PROCEDURE IF EXISTS find_city$$
CREATE PROCEDURE find_city (IN param1 BIGINT UNSIGNED)
BEGIN
SELECT data
FROM cities
WHERE gid = param1;
END$$

DROP PROCEDURE IF EXISTS update_city$$
CREATE PROCEDURE update_city (IN param1 BIGINT UNSIGNED, IN param2 MEDIUMBLOB)
BEGIN
UPDATE cities
SET data = param2
WHERE gid = param1;
END$$

DROP PROCEDURE IF EXISTS get_cities$$
CREATE PROCEDURE get_cities ()
BEGIN
SELECT gid, data
FROM cities;
END$$
