DROP TABLE IF EXISTS guans;
CREATE TABLE IF NOT EXISTS guans (
gid BIGINT UNSIGNED NOT NULL UNIQUE,
data MEDIUMBLOB NOT NULL
)
CHARACTER SET = utf8
ENGINE = InnoDB;

DELIMITER $$

DROP PROCEDURE IF EXISTS add_guan$$
CREATE PROCEDURE add_guan (IN param1 BIGINT UNSIGNED, IN param2 MEDIUMBLOB)
BEGIN
INSERT INTO guans(gid, data)
VALUES(param1, param2);
END$$

DROP PROCEDURE IF EXISTS find_guan$$
CREATE PROCEDURE find_guan (IN param1 BIGINT UNSIGNED)
BEGIN
SELECT data
FROM guans
WHERE gid = param1;
END$$

DROP PROCEDURE IF EXISTS get_guans$$
CREATE PROCEDURE get_guans (IN param1 INT, IN param2 INT)
BEGIN
SELECT gid, data
FROM guans
LIMIT param1, param2;
END$$

DROP PROCEDURE IF EXISTS update_guan$$
CREATE PROCEDURE update_guan (IN param1 BIGINT UNSIGNED, IN param2 MEDIUMBLOB)
BEGIN
UPDATE guans
SET data = param2
WHERE gid = param1;
END$$

DELIMITER ;
