DROP TABLE IF EXISTS rank;
CREATE TABLE IF NOT EXISTS rank (
gid BIGINT UNSIGNED NOT NULL UNIQUE,
data MEDIUMBLOB NOT NULL
)
CHARACTER SET = utf8
ENGINE = InnoDB;

DELIMITER $$

DROP PROCEDURE IF EXISTS add_rank$$
CREATE PROCEDURE add_rank (IN param1 BIGINT UNSIGNED, IN param2 MEDIUMBLOB)
BEGIN
INSERT INTO rank(gid, data)
VALUES(param1, param2);
END$$

DROP PROCEDURE IF EXISTS find_rank$$
CREATE PROCEDURE find_rank (IN param1 BIGINT UNSIGNED)
BEGIN
SELECT data
FROM rank
WHERE gid = param1;
END$$

DROP PROCEDURE IF EXISTS update_rank$$
CREATE PROCEDURE update_rank (IN param1 BIGINT UNSIGNED, IN param2 MEDIUMBLOB)
BEGIN
UPDATE rank
SET data = param2
WHERE gid = param1;
END$$

DROP PROCEDURE IF EXISTS get_rank$$
CREATE PROCEDURE get_rank (IN param1 BIGINT UNSIGNED)
BEGIN
SELECT data
FROM rank
WHERE gid = param1;
END$$

DROP PROCEDURE IF EXISTS get_ranks$$
CREATE PROCEDURE get_ranks ()
BEGIN
SELECT gid, data
FROM rank;
END$$

DELIMITER ;
